services:
  _defaults:
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    autowire: true
    # if you need to do this, you can override this setting on individual services
    public: true

  PN\LocaleBundle\Controller\Administration\:
    resource: '../../Controller/Administration/*'
    tags: [ "controller.service_arguments" ]

  PN\LocaleBundle\Twig\:
    resource: '../../Twig/*'
#    tags: [ "twig.extension" ]

  PN\LocaleBundle\Form\LanguageType:
    arguments: [ "@service_container" ]

  PN\LocaleBundle\Repository\:
    resource: '../../Repository/*'
    tags: [ 'doctrine.repository_service' ]